In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
!wget https://files.grouplens.org/datasets/movielens/ml-100k.zip -O ./ml-data/ml-100k.zip

--2022-02-22 13:43:03--  https://files.grouplens.org/datasets/movielens/ml-100k.zip
Resolving files.grouplens.org (files.grouplens.org)... 128.101.65.152
Connecting to files.grouplens.org (files.grouplens.org)|128.101.65.152|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4924029 (4.7M) [application/zip]
Saving to: './ml-data/ml-100k.zip'

     0K .......... .......... .......... .......... ..........  1%  115K 42s
    50K .......... .......... .......... .......... ..........  2%  229K 31s
   100K .......... .......... .......... .......... ..........  3% 11.4M 20s
   150K .......... .......... .......... .......... ..........  4% 11.7M 15s
   200K .......... .......... .......... .......... ..........  5%  234K 16s
   250K .......... .......... .......... .......... ..........  6% 8.54M 13s
   300K .......... .......... .......... .......... ..........  7% 16.9M 11s
   350K .......... .......... .......... .......... ..........  8%  224K 12s
   400K ........

In [4]:
import zipfile
with zipfile.ZipFile('./ml-data/ml-100k.zip','r') as zip_ref:
    zip_ref.extractall('./ml-data')

In [11]:
columns=['user_id','age','sex','job','zip_code']

data = pd.read_csv('./ml-data/ml-100k/u.user',sep='|',names=columns)
data

user_id  age sex            job zip_code
0          1   24   M     technician    85711
1          2   53   F          other    94043
2          3   23   M         writer    32067
3          4   24   M     technician    43537
4          5   33   F          other    15213
..       ...  ...  ..            ...      ...
938      939   26   F        student    33319
939      940   32   M  administrator    02215
940      941   20   M        student    97229
941      942   48   F      librarian    78209
942      943   22   M        student    77841

[943 rows x 5 columns]

In [12]:
data.shape

(943, 5)

In [17]:
n_users=data.shape[0]
print('Number of users: ', n_users)

Number of users:  943


In [25]:
rate_cols=['user_id','movie_id','rating','timestamp']
rating_base=pd.read_csv('./ml-data/ml-100k/ua.base',sep="\t",names=rate_cols)
rating_test=pd.read_csv('./ml-data/ml-100k/ua.test',sep="\t",names=rate_cols)

In [31]:
rate_train=rating_base.values
rate_test=rating_test.values
rate_train

array([[        1,         1,         5, 874965758],
       [        1,         2,         3, 876893171],
       [        1,         3,         4, 878542960],
       ...,
       [      943,      1188,         3, 888640250],
       [      943,      1228,         3, 888640275],
       [      943,      1330,         3, 888692465]], dtype=int64)

In [32]:
print('Number of training set: ',rate_train.shape[0])
print('Number of training set: ',rate_test.shape[0])

Number of training set:  90570
Number of training set:  9430


In [40]:
item_cols=['movie_id','movie name','release date','URL','unknown', 'Action', 'Adventure',
 'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']

In [44]:
items = pd.read_csv('./ml-data/ml-100k/u.item',sep='|',names=item_cols,encoding='latin-1')
print('number of items: ',items.shape[0])

number of items:  1682


In [52]:
X0=items.values
X_train=X0[:,-19:]
print(X_train)
print(X_train.tolist())

[[0 0 0 ... 0 0 0]
 [0 1 1 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [49]:
from sklearn.feature_extraction.text import TfidfTransformer
transformer = TfidfTransformer(smooth_idf=True,norm='l2')
tfidf=transformer.fit_transform(X_train.tolist()).toarray()

In [50]:
tfidf

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.53676706, 0.65097024, ..., 0.53676706, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
def get_items_rated_by_user(rate_matrix,user_id):
    y=rate_matrix[:,0]
    ids=np.where(y==user_id+1)[0]
    item_ids=rate_matrix